### PR TITLE
add rqlite db dump collector

### PR DESCRIPTION
**Pull request by pavansokkenagaraj**
add rqlite db dump collector

### CODE REVIEW

**Review by chris-sanders — CHANGES_REQUESTED** [review]
You seem to have run a formatter across the file, please don't do that just commit the changes you intend to change. We don't want to be constantly reviewing each persons personal preferences for yaml formatting standards.

Can you rebase out the formatting and just include the change you are trying to land?

**Comment by DexterYan** [comment]
Hi @pavansokkenagaraj 
After run your support bundle collectors for 
```
- exec:
        collectorName: kotsadm-rqlite-db
        name: kots/admin_console
        containerName: rqlite
        selector:
          - app=kotsadm-rqlite
        command:
          - sh
          - -c
          - |
            wget -qO- kotsadm:${RQLITE_PASSWORD}@localhost:4001/db/backup?fmt=sql
        timeout: 10s
```
I got error ` "container rqlite is not valid for pod kotsadm-rqlite-0"`
You can check https://troubleshoot.sh/docs/collect/copy/#containername-optional, I think the `containerName: rqlite` may not need.

After I removed the `containerName: rqlite`. the collector can be run, but there is anthor error `wget: server returned error: HTTP/1.1 401 Unauthorized`. I think it is caused by `${RQLITE_PASSWORD}`

**Comment by pavansokkenagaraj** [comment]
@DexterYan interesting, 

The rqlite statefulset deployed from kotsadm does contain container name `rqlite` and shouldn't err.
https://github.com/replicatedhq/kots/blob/main/deploy/kurl/kotsadm/template/base/rqlite.yaml#L52-L54
I ran on a kotsadm installed cluster and was able to collect resources

**Comment by DexterYan** [comment]
> @DexterYan interesting,
> 
> The rqlite statefulset deployed from kotsadm does contain container name `rqlite` and shouldn't err. https://github.com/replicatedhq/kots/blob/main/deploy/kurl/kotsadm/template/base/rqlite.yaml#L52-L54 I ran on a kotsadm installed cluster and was able to collect resources

Hi @pavansokkenagaraj, I think this issue is caused by my kots version, my kots version is `Replicated KOTS 1.91.1`
if you are using `Replicated KOTS 1.96.1`, should be good.

I uploaded my support bundle for your references, if you are considering backward compatible. Otherwise, looks all good.

[support-bundle-2023-03-21T14_56_58.tar.gz](https://github.com/replicatedhq/troubleshoot-specs/files/11024360/support-bundle-2023-03-21T14_56_58.tar.gz)

**Review by DexterYan — APPROVED** [review]

**Comment by adamancini** [comment]
we merged this one https://github.com/replicatedhq/troubleshoot-specs/pull/62 yesterday; I didn't see this PR at the time

**Comment by pavansokkenagaraj** [comment]
> we merged this one #62 yesterday; I didn't see this PR at the time

@adamancini Thanks, 

the rqlite containerName has changed from `kotsadm-rqlite` to `rqlite`

Like @DexterYan mentioned, lets remove the containerName and let the exec decide on the default container name to collect the rqlite db dump.

So, it is compatible across kots versions

**Review by DexterYan — APPROVED** [review]

**Comment by pavansokkenagaraj** [comment]
🤦🏽  This collector will work only for the kots v1.95.0 and after as the required password to collect the dump  is added to the pod spec in this release
```
        env:
        - name: RQLITE_PASSWORD # this is used by the support bundle collector to get the db backup from rqlite
          valueFrom:
            secretKeyRef:
              name: kotsadm-rqlite
              key: password       
```
https://github.com/replicatedhq/kots/pull/3659/files

**Pull request merged**
