### PR TITLE
chore: Copy syslog files from host if they exist

### PR DESCRIPTION
**Pull request by banjoh**

### CODE REVIEW

**Comment by adamancini** [comment]
my only suggestion would be that not all systems call the syslog "syslog" like I think on some systems it might be `/var/log/messages` - otherwise LGTM

**Comment by adamancini** [comment]
actually, I'm doing a little more reading and I don't think `messages` file is relevant anymore

**Review by adamancini — APPROVED** [review]

**Comment by adamancini** [comment]
@banjoh maybe we should also grab something like `journalctl --no-pager --output=short-iso` to grab everything from journald

**Comment by banjoh** [comment]
> my only suggestion would be that not all systems call the syslog "syslog" like I think on some systems it might be `/var/log/messages` - otherwise LGTM

I'll merge and follow up with another PR

**Pull request merged**
